tasks:

    -initialize:
      name: 'Initialize'

    -gate:
        name: 'Gate'

    -buoys:
        name: 'Buoys'


    -maneuver:
        name: 'Maneuver'

    -bins:
        name: 'Bins'

    -torpedo:
        name: 'Torpedo'

    -octagon:
        name: 'Octagon'

    -square:
        name: 'Square'
