tasks:

  -initialize:
    name: 'Initialize'
    seconds: 10
    milliseconds: 0

  -gate:
      name: 'Gate'
      timeout: 60

  -buoys:
      timeout: 60
      name: 'Buoys'


  -maneuver:
      timeout: 60
      name: 'Maneuver'

  -bins:
      timeout: 60
      name: 'Bins'



  -torpedo:
      timeout: 60
      name: 'Torpedo'

  -octagon:
         name: 'Octagon'
         timeout: 60

  -square:
      name: 'Square'
