move_type:
  - move_name: x-axis
    x        : 1
    y        : 0
    z        : 0
  - move_name: y-axis
    x        : 0
    y        : 1
    z        : 0
  - move_name: z-axis
    x        : 0
    y        : 0
    z        : 1
 
