initialize:
  seconds: 10
  milliseconds: 0
move_type:
  - move: first
    time:
          seconds : 10
          milliseconds : 0
    velocity:
              Pose:
                    x: 1
                    y: 2
                    z: 3

  - move: second
    x        : 0
    y        : 1
    z        : 0
  - move: third
    x        : 0
    y        : 0
    z        : 1
